### ISSUE TITLE
Api is updated

### ISSUE THREAD

**Issue by XOTAB1CH** [nimroddolev/akuvox#10]
### System Health details

Raspberry PI 4B + Argon One M2 SSD

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/akuvox/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

There are new fields in the server list, passwd instead of auth_token, I replaced all auth_token fields with passwd and it worked

### Reproduction steps

replace all fields "auth_token" to "passwd" in files 

api.py
config_flow.py
entity.py
translations/en.json

### Debug logs

```text
null
```

**Comment by nimroddolev** [comment]
Hi @XOTAB1CH thanks for opening this task.
I don't see the new `passwd` field in any of the API responses, there must be a difference/s between our accounts and/or the API version we are using.
To help pinpoint, could you please share the device you have the SmartPlus app installed on, as well as anything else which might be relevant?

**Comment by XOTAB1CH** [comment]
IOS 17.0.2, last version of app
Check via mitmproxy https://gate.ecloud.akuvox.com:8600/servers_list when auth in app
![image](https://github.com/nimroddolev/akuvox/assets/30771106/f148ef7c-259a-4893-9595-6705f16c0a00)

**Comment by nimroddolev** [comment]
Thanks for the quick reply. We're both on iOS and in the servers_list response we are both on api-version 6.6 but have different fields in the response JSON...strange.
I will handle both options and push a bugfix release. I would appreciate it if you could please test the new version once available.

**Comment by XOTAB1CH** [comment]
Thanks

**Comment by nimroddolev** [comment]
Hi @XOTAB1CH, can you please apply the change in commit |https://github.com/nimroddolev/akuvox/commit/903c42c01e1f677966245c5f430cd4cfeeccabc7 and let me know if the issue is resolved for you?

**Comment by XOTAB1CH** [comment]
Not work, maybe field "auth_token" must be as optional in json, when i also changed user agent and x-cloud-lang and accept-language, and then its work, and replace all auth_token to passwd fields, my region Europe/UA

**Comment by XOTAB1CH** [comment]
home assistant didn't update the repository, added the field manually via file editor and everything worked

**Comment by nimroddolev** [comment]
Excellent. I have released a new version with the fix.
