### ISSUE TITLE
Token Method is not working

### ISSUE THREAD

**Issue by prnzngr** [nimroddolev/akuvox#22]
## System Information

version | core-2023.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4951
Installed Version | 1.33.0
Stage | running
Available Repositories | 1359
Downloaded Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 17.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), ESPHome (2023.12.3), Mosquitto broker (6.4.0), Piper (1.4.0), Whisper (1.0.0), Studio Code Server (5.14.2), evcc (0.123.1), File editor (5.7.0), Cloudflared (4.2.12), Advanced SSH & Web Terminal (17.0.0), Zigbee2MQTT (1.34.0-1), openWakeWord (1.8.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 10
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 16, 2023 at 17:35
-- | --
current_recorder_run | December 22, 2023 at 13:26
estimated_db_size | 447.60 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/akuvox/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I used the provided tokens which I found via mitmproxy but "Sign in failed"
My auth_token is named passwd as you already mentioned in documentation

### Reproduction steps

1. logout of app
2. login in app
3. read tokens in mitmproxy
...

### Debug logs

```text
no logs
```

**Comment by nimroddolev** [comment]
Hi @prnzngr, I'm sorry you've been having issues.
I just released a new beta version which I hope addresses the issues you've been having. Please upgrade and let me know if it solves your problem.

To install the new beta version:

1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=akuvox&category=integration" title="Akuvox HACS repository" target="_blank">Akuvox SmartPlus repository in HACS</a>

1. Click on the `⋮` button in the top right

1. Select the `↻ Redownload` option

1. Enable the `Show beta versions` option

1. Select version `v0.0.7-beta1` from the updated version drop-down list

**Comment by nimroddolev** [comment]
I assume the new version fixed your issue and I am now closing the issue. If you are still experiencing the problem please reopen the issue with debug log messages:

1. Set the logging level for akuvox to `debug`:
```
service: logger.set_level
data:
  custom_components.akuvox: debug
```

2. Add the integration and perform the sign in.

3. Check your log messages in Home Assistant:
```
https://{YOUR_HOME_ASSISTANT_ADDRESS}:8123/config/logs?filter=akuvox
```
and click `LOAD FULL LOGS`
