### ISSUE TITLE
SMS code request failed. Check your phone number.

### ISSUE THREAD

**Issue by SirNoble** [nimroddolev/akuvox#23]
### System Health details

<html>
<body>

version | core-2023.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Australia
config_dir | /config

</body>
</html>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/akuvox/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When trying to set up the integration, I can't sign in via the SMS or App token methods.  When the correct details are inputted into SMS Verification (Country code - +61, Australia)  and my number it says SMS code request failed. check your phone number.
Trying via the sign-in app token method gives me the error "Sign in failed. Please check the values entered and try again"

### Reproduction steps

1. Re-installed HACS plugin
2. Tried with multiple numbers linked to Akuvox, all the with the same issue. 
3. Tried signing in with the mobile number again into the iPhone Akuvox application and had no issues logging in.

**Comment by nimroddolev** [comment]
Hi @SirNoble, I replied to you in the Home Assistant forum, but in case you missed the mesage:  I just released a new beta version, v0.0.7-beta1 which adds support for regions outside Europe. Please upgrade and let me know if you can now sign in and view your devices.

To install the new beta version:

1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=akuvox&category=integration" title="Akuvox HACS repository" target="_blank">Akuvox SmartPlus repository in HACS</a>

1. Click on the `⋮` button in the top right

1. Select the `↻ Redownload` option

1. Enable the `Show beta versions` option

1. Select version `v0.0.7-beta1` from the updated version drop-down list

**Comment by SirNoble** [comment]
> Hi @SirNoble, I replied to you in the Home Assistant forum, but in case you missed the mesage: I just released a new beta version, v0.0.7-beta1 which adds support for regions outside Europe. Please upgrade and let me know if you can now sign in and view your devices.
> 
> To install the new beta version:
> 
> 1. Open the [Akuvox SmartPlus repository in HACS](https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=akuvox&category=integration)
> 2. Click on the `⋮` button in the top right
> 3. Select the `↻ Redownload` option
> 4. Enable the `Show beta versions` option
> 5. Select version `v0.0.7-beta1` from the updated version drop-down list

That's amazing thank you, now working perfectly.
